const assert=require('node:assert/strict');
const {DatabaseSync}=require('node:sqlite');
const {readFileSync,readdirSync}=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const {pathToFileURL}=require('node:url');
const service=require(path.join(process.env.HISAB_TEST_BUILD,'service.js'));
const ledger=require(path.join(process.env.HISAB_TEST_BUILD,'ledger.js'));
const copy=v=>v==null?v:JSON.parse(JSON.stringify(v));
function database(){const sqlite=new DatabaseSync(':memory:');for(const f of readdirSync('drizzle').filter(f=>f.endsWith('.sql')).sort())sqlite.exec(readFileSync(path.join('drizzle',f),'utf8'));return {sqlite,prepare(sql){let args=[];const execute=()=>{const q=sqlite.prepare(sql);if(/^SELECT/i.test(sql))return {results:q.all(...args)};const r=q.run(...args);return {results:[],meta:{changes:Number(r.changes)}};};return {bind(...v){args=v;return this;},async run(){return execute();},async first(){return sqlite.prepare(sql).get(...args)||null;},async all(){return {results:sqlite.prepare(sql).all(...args)};},_execute:execute};},async batch(statements){sqlite.exec('BEGIN');try{const r=statements.map(s=>s._execute());sqlite.exec('COMMIT');return r;}catch(e){sqlite.exec('ROLLBACK');throw e;}}};}
function memoryStore(){let value=null,tail=Promise.resolve(),fail=false;return {async read(){await tail;return copy(value);},update(fn){const result=tail.then(()=>{if(fail){fail=false;throw new Error('QuotaExceeded');}const next=fn(copy(value));value=copy(next);return copy(value);});tail=result.catch(()=>{});return result;},failNext(){fail=true;}};}
let checks=0;const eq=(a,b)=>{assert.deepEqual(a,b);checks++;};
(async()=>{
  await import(pathToFileURL(path.resolve('public/jf-offline.js')).href);
  const db=database(),store=memoryStore();let online=true,lostResponse=false,auth=true,owner='owner-a';
  const request=async body=>{if(!online)throw new TypeError('Network down');if(!auth)throw Object.assign(new Error('Sign in'),{status:401});if(!body)return service.readState(db,owner);const result=await service.syncEntry(db,owner,body);if(lostResponse){lostResponse=false;throw new TypeError('Connection lost AFTER commit');}return result;};
  const engine=()=>global.JasimFlowOffline.createEngine({store,request});let app=engine();await app.sync();eq((await app.status()).ready,true);
  const payload=(kind,amount,extra={})=>({action:'save',id:crypto.randomUUID(),kind,amount:String(amount),category:kind==='income'?'Work':'Food',account:'Cash',date:'2026-08-01',person:'Rahim',...extra});
  online=false;const income=payload('income',100),expense=payload('expense',30),loan=payload('borrow',200),payment=payload('repay',50,{parent_id:loan.id});for(const p of [income,expense,loan,payment])await app.enqueue(p);
  eq((await app.status()).pending,4);eq(ledger.summarize((await app.read()).entries).balance,22000);app=engine();eq((await app.read()).entries.length,4);eq((await app.status()).pending,4);
  online=true;lostResponse=true;await app.sync();eq((await app.status()).pending,4);eq((await service.readState(db,owner)).entries.length,1);await app.sync();eq((await app.status()).pending,0);eq((await service.readState(db,owner)).entries.length,4);eq(ledger.summarize((await app.read()).entries).balance,22000);
  // Two offline edits depend on one another and survive a process restart.
  online=false;await app.enqueue({...income,edit:true,amount:'120'});await app.enqueue({...income,edit:true,amount:'140'});app=engine();online=true;await app.sync();eq((await app.status()).pending,0);eq((await service.readState(db,owner)).entries.find(e=>e.id===income.id).amount,14000);
  // Another device's edit is not overwritten without an explicit resolution.
  await app.enqueue({...income,edit:true,amount:'145'});await service.saveEntry(db,owner,{...income,edit:true,amount:'160'});await app.sync();eq((await app.status()).pending,1);assert.ok((await app.status()).issue);checks++;eq((await service.readState(db,owner)).entries.find(e=>e.id===income.id).amount,16000);
  await app.reviseIssue('152','Confirmed correction');await app.sync();eq((await app.status()).pending,0);eq((await service.readState(db,owner)).entries.find(e=>e.id===income.id).amount,15200);
  // A response-lost edit must acknowledge its ORIGINAL version, not a newer
  // value from another device, before applying a dependent edit.
  await app.enqueue({...income,edit:true,amount:'180'});await app.enqueue({...income,edit:true,amount:'200'});lostResponse=true;await app.sync();await service.saveEntry(db,owner,{...income,edit:true,amount:'190'});await app.sync();eq((await app.status()).pending,1);assert.ok((await app.status()).issue);checks++;eq((await service.readState(db,owner)).entries.find(e=>e.id===income.id).amount,19000);await app.reviseIssue('200','Reviewed latest version');await app.sync();eq((await app.status()).pending,0);
  await assert.rejects(()=>app.enqueue(payload('repay',151,{parent_id:loan.id})));checks++;eq((await app.status()).pending,0);
  // Cross-device repayments are guarded again on the server, not just locally.
  await app.enqueue(payload('repay',100,{parent_id:loan.id}));await service.saveEntry(db,owner,payload('repay',80,{parent_id:loan.id}));await app.sync();assert.ok((await app.status()).issue);checks++;await app.reviseIssue('70','Remaining balance');await app.sync();eq((await app.status()).pending,0);eq(ledger.summarize((await app.read()).entries).payable,0);
  // An interrupted authenticated session retains queued records but hides data.
  await app.enqueue(payload('expense',5));auth=false;await app.sync();eq((await app.status()).locked,true);eq(await app.read(),null);eq((await app.status()).pending,1);auth=true;owner='owner-b';await app.sync();eq((await app.status()).locked,true);eq((await service.readState(db,owner)).entries.length,0);owner='owner-a';await app.sync();eq((await app.status()).locked,false);eq((await app.status()).pending,0);
  store.failNext();await assert.rejects(()=>app.enqueue(payload('income',999)));checks++;eq((await app.status()).pending,0);
  await app.enqueue(payload('income',17));await assert.rejects(()=>app.clear());checks++;const backup=await app.backup();eq(backup.pending.length,1);assert.ok(!JSON.stringify(backup).includes('bin_hash'));checks++;
  const other=engine();await Promise.all([app.sync(),other.sync()]);eq((await app.status()).pending,0);eq(db.sqlite.prepare('SELECT COUNT(*) AS n FROM entries WHERE amount=1700').get().n,1);
  // Receipts reject altered retries and survive subsequent edits/deletion.
  const p=payload('expense',9),op={id:crypto.randomUUID(),payload:p,baseUpdatedAt:null};const receipt=await service.syncEntry(db,owner,{ownerKey:owner,operation:op});await service.trashEntry(db,owner,p.id);const retry=await service.syncEntry(db,owner,{ownerKey:owner,operation:op});eq(retry.alreadySaved,true);eq(retry.entryUpdatedAt,receipt.entryUpdatedAt);await assert.rejects(()=>service.syncEntry(db,owner,{ownerKey:owner,operation:{...op,payload:{...p,amount:'10'}}}),e=>e.status===409);checks++;
  const count=db.sqlite.prepare('SELECT COUNT(*) AS n FROM sync_receipts').get().n;await assert.rejects(()=>service.syncEntry(db,owner,{ownerKey:owner,operation:{id:crypto.randomUUID(),payload:payload('repay',1,{parent_id:loan.id}),baseUpdatedAt:null}}));checks++;eq(db.sqlite.prepare('SELECT COUNT(*) AS n FROM sync_receipts').get().n,count);
  // An explicit local discard removes dependents; no server record is changed.
  await app.sync();const pending=payload('borrow',10);await app.enqueue(pending);await app.enqueue(payload('repay',3,{parent_id:pending.id}));await service.saveEntry(db,owner,pending);await app.sync();assert.ok((await app.status()).issue);checks++;await app.discardIssue();eq((await app.status()).pending,0);eq((await service.readState(db,owner)).entries.find(e=>e.id===pending.id).amount,1000);
  // A successful online deletion stays deleted locally if refresh loses network.
  await app.sync();await service.trashEntry(db,owner,expense.id);await app.acknowledge({action:'trash',id:expense.id});online=false;eq((await app.read()).entries.some(e=>e.id===expense.id),false);eq((await app.backup()).state.entries.some(e=>e.id===expense.id),false);const preferences={...(await app.read()).prefs,budget:5500};await app.acknowledge({action:'prefs',prefs:preferences});eq((await app.read()).prefs.budget,5500);online=true;
  // Exercise the actual worker handlers with Cache/Fetch test doubles.
  const handlers={},cacheStores=new Map();let network=true,networkCalls=0;const caches={async keys(){return [...cacheStores.keys()];},async open(name){if(!cacheStores.has(name))cacheStores.set(name,new Map());const map=cacheStores.get(name),key=r=>typeof r==='string'?new URL(r,'https://test.example').pathname:new URL(r.url).pathname;return {async put(r,response){map.set(key(r),response.clone());},async match(r){return map.get(key(r))?.clone();},async keys(){return [...map.keys()];}};},async delete(name){return cacheStores.delete(name);},async match(r){for(const k of cacheStores.keys()){const result=await (await caches.open(k)).match(r);if(result)return result;}}};
  const self={__JF_CACHE_VERSION:'jasimflow-shell-test',__JF_PRECACHE:['/assets/app.js','/assets/app.css'],JasimFlowOffline:{createEngine:()=>({sync:async()=>{},status:async()=>({pending:0})})},location:{origin:'https://test.example'},addEventListener:(event,fn)=>handlers[event]=fn,skipWaiting:async()=>{},clients:{claim:async()=>{},matchAll:async()=>[]}};
  vm.runInNewContext(readFileSync('public/sw.js','utf8'),{self,caches,URL,importScripts:()=>{},fetch:async url=>{networkCalls++;if(!network)throw new Error('offline');return new Response(url==='/'?'<html><title>JasimFlow</title><body>shell only</body></html>':'asset',{headers:{'content-type':url==='/'?'text/html':'text/javascript'}});},Set,Promise,Error});
  await new Promise((resolve,reject)=>handlers.install({waitUntil:p=>p.then(resolve,reject)}));await new Promise((resolve,reject)=>handlers.activate({waitUntil:p=>p.then(resolve,reject)}));network=false;const before=networkCalls;let response;handlers.fetch({request:{url:'https://test.example/',method:'GET',mode:'navigate'},respondWith:p=>response=p});eq((await (await response).text()).includes('JasimFlow'),true);eq(networkCalls,before);
  for(const url of ['/api/hisab','/api/hisab?view=bin','/login','/cdn-cgi/access/logout']){let intercepted=false;handlers.fetch({request:{url:'https://test.example'+url,method:'GET',mode:'navigate'},respondWith:()=>intercepted=true});eq(intercepted,false);}
  eq((await (await caches.open('jasimflow-shell-test')).keys()).sort(),['/','/assets/app.css','/assets/app.js']);
  console.log(`${checks} offline/sync checks passed: durable queue restart, immediate local totals, response loss, idempotency, chained edits, conflict resolution, cross-device repayments, owner isolation, expired auth, write failure, leases, backups, receipt atomicity, offline shell and network-only Bin/auth.`);
})().catch(error=>{console.error(error);process.exitCode=1;});
