"use client";
import { useLanguage } from "@/components/language";
import { useEffect,useId,useRef,useState } from "react";
import { ArrowDownLeft,ArrowUpRight,Handshake,Zap,Check,ChevronDown,Star,Utensils,Bus,Users,Shirt,ShoppingBag,Globe,Smartphone,Heart,Briefcase,ChartNoAxesCombined,House,Shapes,Receipt,Wallet } from "lucide-react";
import { Tabs,TabsList,TabsTrigger } from "@/components/ui/tabs";
import { RadioGroup,RadioGroupItem } from "@/components/ui/radio-group";
import { Select,SelectTrigger,SelectContent,SelectItem,SelectValue } from "@/components/ui/select";
import { api } from "@/lib/client-api";
import { amountToMinor,ACCOUNTS,isPayable,money,outstanding,today,type Entry,type Kind,type Prefs } from "@/lib/ledger";

import { CandleLoader, entryFeedback } from "./pulse-ledger";

export const categoryIcons:Record<string,typeof Utensils>={Food:Utensils,Transport:Bus,Friends:Users,Family:House,Dress:Shirt,Product:ShoppingBag,Online:Globe,"Mobile/Internet":Smartphone,Bills:Receipt,Health:Heart,Work:Briefcase,Trading:ChartNoAxesCombined,"Product Sell":ShoppingBag,Others:Shapes};
export function Picker({value,onChange,items,label}:{value:string;onChange:(v:string)=>void;items:{value:string;label:string}[];label:string}){return <Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label} className="picker"><SelectValue placeholder={label}/></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.value} value={i.value}>{i.label}</SelectItem>)}</SelectContent></Select>;}

export default function QuickEntry({prefs,entries,onSaved,initial,defaultKind="expense",parent,compact=false}:{prefs:Prefs;entries:Entry[];onSaved:()=>Promise<void>|void;initial?:Entry;defaultKind?:Kind;parent?:Entry;compact?:boolean}){
  const { t, kindLabel, categoryLabel } = useLanguage();

  const [kind,setKind]=useState<Kind>(initial?.kind||defaultKind),[amount,setAmount]=useState(initial?String(initial.amount/100):""),[category,setCategory]=useState(initial?.category||""),[account,setAccount]=useState(initial?.account||prefs.defaultAccount),[toAccount,setToAccount]=useState(initial?.to_account||"bKash"),[person,setPerson]=useState(initial?.person||parent?.person||""),[date,setDate]=useState(initial?.date||today()),[dueDate,setDueDate]=useState(initial?.due_date||""),[note,setNote]=useState(initial?.note||""),[channel,setChannel]=useState(initial?.channel||""),[more,setMore]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const [pulse,setPulse]=useState(false);const saving=useRef(false);const pulseTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
  useEffect(()=>()=>{if(pulseTimer.current)clearTimeout(pulseTimer.current);},[]);
  const fieldId=useId();const requestId=useRef<string>(initial?.id||"");const amountRef=useRef<HTMLInputElement>(null);
  const isRoot=["borrow","lend","credit","old_borrow","old_lend"].includes(kind), payment=["repay","collect"].includes(kind),categorized=["income","expense","credit"].includes(kind);
  const categories=(kind==="income"?prefs.inCategories:prefs.outCategories).map((v,i)=>({v,i})).sort((a,b)=>Number(prefs.favorites.includes(b.v))-Number(prefs.favorites.includes(a.v))||a.i-b.i).map(x=>x.v);
  const chooseKind=(v:Kind)=>{setKind(v);setCategory("");setError("");if(["income","expense"].includes(v)){setPerson("");setDueDate("");}};
  async function save(e:React.FormEvent){e.preventDefault();if(saving.current)return;if(categorized&&!category){setError("ক্যাটাগরি বেছে নিন।");return;}saving.current=true;setBusy(true);setError("");try{if(!requestId.current)requestId.current=crypto.randomUUID();const savedResult=await api<{queued?:boolean}>({action:"save",id:requestId.current,edit:!!initial,kind,amount,category,account,to_account:toAccount,person,date,due_date:dueDate,note,channel,parent_id:initial?.parent_id||parent?.id});entryFeedback({kind,amount:amountToMinor(amount),queued:!!savedResult.queued,edited:!!initial});setPulse(true);if(pulseTimer.current)clearTimeout(pulseTimer.current);pulseTimer.current=setTimeout(()=>setPulse(false),480);if(!initial){requestId.current="";setAmount("");setNote("");setDate(today());setDueDate("");}await onSaved();amountRef.current?.focus();}catch(e){setError(e instanceof Error?e.message:"আবার চেষ্টা করুন।");}finally{saving.current=false;setBusy(false);}}
  const tab=kind==="income"?"income":kind==="expense"?"expense":"borrow";
  return <section className={"quick-entry "+(compact?"compact ":"")+(pulse?"entry-saved":"")} data-kind={kind}>
    {!initial&&!parent&&!["opening","transfer"].includes(kind)&&<><div className="section-heading"><div><span className="eyebrow">{t("QUICK ENTRY")}</span><h2>{t("হিসাব রাখো, ফ্লো-তে থাকো")}</h2></div><span className="quick-icon"><Zap size={20}/></span></div><Tabs value={tab} onValueChange={v=>chooseKind(v as Kind)}><TabsList className="entry-tabs"><TabsTrigger value="expense"><ArrowUpRight size={16}/>{t("Cash Out")}</TabsTrigger><TabsTrigger value="income"><ArrowDownLeft size={16}/>{t("Cash In")}</TabsTrigger><TabsTrigger value="borrow"><Handshake size={16}/>{t("ঋণ")}</TabsTrigger></TabsList></Tabs></>}
    <form onSubmit={save}><fieldset disabled={busy}>
      {parent&&<div className="payment-info"><Handshake size={20}/><div><strong>{parent.person}</strong><span>{t("বাকি")} {money(outstanding(parent,entries))}</span></div><button className="text-button" type="button" onClick={()=>setAmount(String(outstanding(parent,entries)/100))}>{t("পুরো টাকা")}</button></div>}
      {isRoot&&!initial&&<div className="field"><label>{t("কী ধরনের হিসাব?")}</label><Picker label={t("ঋণের ধরন")} value={kind} onChange={v=>chooseKind(v as Kind)} items={["borrow","lend","credit","old_borrow","old_lend"].map(v=>({value:v,label:kindLabel(v as Kind)}))}/></div>}
      {isRoot&&<div className="field"><label htmlFor={fieldId+"-entry-person"}>{isPayable({kind} as Entry)?t("কার কাছে টাকা দেবে?"):t("কার কাছে টাকা পাবে?")}</label><input id={fieldId+"-entry-person"} placeholder={t("ব্যক্তির নাম")} value={person} onChange={e=>setPerson(e.target.value)} required maxLength={100} list={fieldId+"-known-people"}/><datalist id={fieldId+"-known-people"}>{[...new Set(entries.map(e=>e.person).filter(Boolean))].map(p=><option value={p} key={p}/>)}</datalist></div>}
      <label className="amount-label" htmlFor={fieldId+"-entry-amount"}>{t("টাকার পরিমাণ")}</label><div className="amount-input"><span>{t("৳")}</span><input ref={amountRef} id={fieldId+"-entry-amount"} inputMode="decimal" autoComplete="off" placeholder="0" value={amount} onChange={e=>setAmount(e.target.value)} required aria-label={t("টাকার পরিমাণ")}/></div>
      <div className="amount-shortcuts">{[50,100,200,500].map(n=><button key={n} type="button" onClick={()=>setAmount(String(n))} className={Number(amount)===n?"selected":""}>{t("৳")}{n}</button>)}</div>
      {categorized&&<div className="category-section"><div className="field-label"><span>{t("ক্যাটাগরি")}</span>{categories.length>6&&<button type="button" className="text-button" onClick={()=>setMore(!more)}>{more?t("কম দেখাও"):t("সব দেখাও")}<ChevronDown size={14}/></button>}</div><RadioGroup value={category} onValueChange={v=>{setCategory(v);setError("");}} className="category-grid" aria-label={t("ক্যাটাগরি")}>{(more?categories:categories.slice(0,6)).map(c=>{const Icon=categoryIcons[c]||Shapes;return <label key={c} className={"category-tile "+(category===c?"chosen":"")}><RadioGroupItem value={c} className="sr-only"/><Icon size={15}/><span>{categoryLabel(c)}</span>{prefs.favorites.includes(c)&&<Star className="favorite-indicator" size={9}/>}</label>;})}</RadioGroup></div>}
      <div className={"entry-notes "+(categorized?"with-channel":"")}> <div className="field"><label htmlFor={fieldId+"-entry-note"}>{t("নোট · ঐচ্ছিক")}</label><input id={fieldId+"-entry-note"} placeholder={t("কিছু মনে রাখতে চাইলে…")} value={note} onChange={e=>setNote(e.target.value)} maxLength={1000}/></div>{categorized&&<div className="field"><label htmlFor={fieldId+"-entry-channel"}>{t("কোথায় / মাধ্যম · ঐচ্ছিক")}</label><input id={fieldId+"-entry-channel"} placeholder={t("যেমন: Online, দোকান")} value={channel} onChange={e=>setChannel(e.target.value)} maxLength={50}/></div>} </div>
      <div className="account-row"><span><Wallet size={17}/> {kind==="transfer"?t("যেখান থেকে"):t("অ্যাকাউন্ট")}</span><Picker label={t("অ্যাকাউন্ট")} value={account} onChange={v=>{setAccount(v);if(toAccount===v)setToAccount(ACCOUNTS.find(a=>a!==v)!);}} items={ACCOUNTS.map(a=>({value:a,label:a}))}/></div>
      {kind==="transfer"&&<div className="field"><label>{t("যে অ্যাকাউন্টে যাবে")}</label><Picker label={t("গন্তব্য অ্যাকাউন্ট")} value={toAccount} onChange={setToAccount} items={ACCOUNTS.filter(a=>a!==account).map(a=>({value:a,label:a}))}/></div>}
      {["old_borrow","old_lend","credit"].includes(kind)&&<p className="field-hint">{kind==="credit"?t("খরচ ও ঋণ বাড়বে। এখন নগদ টাকা কমবে না।"):t("আগের বকেয়া যোগ হবে। বর্তমান ব্যালেন্স বদলাবে না।")}</p>}
      <details className="entry-details" open={initial?true:undefined}><summary><span>{t("তারিখ ও অন্যান্য")}</span><span>{date===today()?t("আজ"):date}<ChevronDown size={14}/></span></summary><div className="details-content"><div className="field"><label htmlFor={fieldId+"-entry-date"}>{t("লেনদেনের তারিখ")}</label><input id={fieldId+"-entry-date"} type="date" max={today()} value={date} onChange={e=>setDate(e.target.value)} required/></div>{isRoot&&<div className="field"><label htmlFor={fieldId+"-entry-due"}>{t("পরিশোধের তারিখ · ঐচ্ছিক")}</label><input id={fieldId+"-entry-due"} type="date" min={date} value={dueDate} onChange={e=>setDueDate(e.target.value)}/></div>}</div></details>
      {error&&<p className="form-error" role="alert">{t(error)}</p>}<button type="submit" className="primary save-button">{busy?<CandleLoader/>:pulse?<Check size={19}/>:<Zap size={19}/>} {busy?t("সেভ হচ্ছে…"):pulse?t("সেভ হয়েছে ✓"):initial?t("পরিবর্তন সেভ করো"):payment?t("পরিশোধ সেভ করো"):t("এন্ট্রি সেভ করো")}</button>
    </fieldset></form><p className="entry-footnote">{payment?t("ঋণ ও ব্যালেন্স একসঙ্গে আপডেট হবে"):t("৳ BDT · বাংলাদেশ সময় (UTC+6)")}</p>
  </section>;
}
