export const ACCOUNTS = ["Cash", "bKash", "Nagad", "Bank"];
export const IN_CATEGORIES = ["Work", "Trading", "Family", "Product Sell", "Others"];
export const OUT_CATEGORIES = ["Food", "Transport", "Friends", "Family", "Dress", "Product", "Online", "Mobile/Internet", "Bills", "Health", "Others"];
export const CATEGORY_BN: Record<string,string> = {Food:"খাবার",Transport:"যাতায়াত",Friends:"বন্ধু",Family:"পরিবার",Dress:"পোশাক",Product:"কেনাকাটা",Online:"অনলাইন", "Mobile/Internet":"মোবাইল / ইন্টারনেট",Bills:"বিল",Health:"চিকিৎসা",Others:"অন্যান্য",Work:"কাজ",Trading:"ট্রেডিং","Product Sell":"পণ্য বিক্রি"};
export type Kind = "income"|"expense"|"borrow"|"lend"|"repay"|"collect"|"credit"|"opening"|"transfer"|"old_borrow"|"old_lend";
export const KIND_LABEL: Record<Kind,string> = {income:"Cash In",expense:"Cash Out",borrow:"ঋণ নিয়েছি",lend:"ধার দিয়েছি",repay:"ঋণ পরিশোধ",collect:"পাওনা ফেরত",credit:"বাকিতে কেনা",opening:"শুরুর ব্যালেন্স",transfer:"Transfer",old_borrow:"আগের ঋণ",old_lend:"আগের পাওনা"};
export interface Entry { _pending?:boolean; _operationId?:string; id:string; owner?:string; kind:Kind; amount:number; category:string; account:string; to_account:string; person:string; parent_id:string|null; date:string; due_date:string; note:string; channel:string; created_at:string; updated_at:string; deleted_at:string|null; delete_group:string|null }
export interface Prefs { defaultAccount:string; budget:number; favorites:string[]; inCategories:string[]; outCategories:string[]; }
export const DEFAULT_PREFS:Prefs = {defaultAccount:"Cash",budget:0,favorites:["Food","Transport","Work"],inCategories:IN_CATEGORIES,outCategories:OUT_CATEGORIES};
export interface AppData { entries:Entry[]; prefs:Prefs; binConfigured:boolean; ownerKey?:string; }
export const isDebt = (e:Entry) => ["borrow","lend","credit","old_borrow","old_lend"].includes(e.kind);
export const isPayable = (e:Entry) => ["borrow","credit","old_borrow"].includes(e.kind);
export function cashChange(e:Entry) { if(["income","borrow","collect","opening"].includes(e.kind))return e.amount; if(["expense","lend","repay"].includes(e.kind))return -e.amount; return 0; }
export function accountBalance(entries:Entry[], account:string) {return entries.filter(e=>!e.deleted_at).reduce((n,e)=>n+(e.account===account?(e.kind==="transfer"?-e.amount:cashChange(e)):0)+(e.kind==="transfer"&&e.to_account===account?e.amount:0),0);}
export function outstanding(root:Entry, entries:Entry[]) {return root.amount-entries.filter(e=>e.parent_id===root.id&&!e.deleted_at).reduce((n,e)=>n+e.amount,0);}
export function summarize(entries:Entry[]) {const active=entries.filter(e=>!e.deleted_at);return {balance:active.reduce((s,e)=>s+cashChange(e),0),income:active.filter(e=>e.kind==="income").reduce((s,e)=>s+e.amount,0),expense:active.filter(e=>["expense","credit"].includes(e.kind)).reduce((s,e)=>s+e.amount,0),cashIn:active.filter(e=>e.kind!=="opening").reduce((s,e)=>s+Math.max(0,cashChange(e)),0),cashOut:active.reduce((s,e)=>s+Math.max(0,-cashChange(e)),0),borrowed:active.filter(e=>["borrow","credit"].includes(e.kind)).reduce((s,e)=>s+e.amount,0),repaid:active.filter(e=>e.kind==="repay").reduce((s,e)=>s+e.amount,0),payable:active.filter(e=>isDebt(e)&&isPayable(e)).reduce((s,e)=>s+outstanding(e,active),0),receivable:active.filter(e=>isDebt(e)&&!isPayable(e)).reduce((s,e)=>s+outstanding(e,active),0)};}
export function today() {return new Intl.DateTimeFormat("en-CA",{timeZone:"Asia/Dhaka",year:"numeric",month:"2-digit",day:"2-digit"}).format(new Date());}
export function money(n:number) {return "৳"+new Intl.NumberFormat("en-IN",{maximumFractionDigits:2,minimumFractionDigits:n%100?2:0}).format(n/100);}
export function dateLabel(d:string) {return new Intl.DateTimeFormat("bn-BD",{day:"numeric",month:"short",timeZone:"Asia/Dhaka"}).format(new Date(d+"T12:00:00+06:00"));}
export type Period = "week"|"month"|"year"|"custom";
export function periodBounds(period:Period, anchor=today()):[string,string] {const d=new Date(anchor+"T00:00:00Z"), y=d.getUTCFullYear(),m=d.getUTCMonth(); const iso=(v:Date)=>v.toISOString().slice(0,10); if(period==="year")return [`${y}-01-01`,`${y}-12-31`]; if(period==="week"){d.setUTCDate(d.getUTCDate()-((d.getUTCDay()+1)%7)); const end=new Date(d);end.setUTCDate(d.getUTCDate()+6);return [iso(d),iso(end)];}return [iso(new Date(Date.UTC(y,m,1))),iso(new Date(Date.UTC(y,m+1,0)))];}
export function filterPeriod(entries:Entry[], start:string,end:string){return entries.filter(e=>!e.deleted_at&&e.date>=start&&e.date<=end);}
export function amountToMinor(value:unknown) {const s=String(value??"").trim();if(!/^\d+(\.\d{1,2})?$/.test(s))throw new Error("সঠিক টাকার পরিমাণ লিখুন (সর্বোচ্চ ২ দশমিক)।");const [whole,fraction=""]=s.split(".");const n=Number(whole)*100+Number(fraction.padEnd(2,"0"));if(!Number.isSafeInteger(n)||n<=0||n>100000000000)throw new Error("পরিমাণ ৳০-এর বেশি এবং ৳১০০ কোটির মধ্যে হতে হবে।");return n;}
