import "../public/jf-offline.js";
import type {AppData} from "./ledger";

export interface SyncIssue {serverAmount?:number;id:string;payload:Record<string,unknown>;amount:number;error:string;createdAt:string}
export interface OfflineStatus {pending:number;lastSync:string|null;error:string;locked:boolean;issue:SyncIssue|null;syncing:boolean;ready:boolean}
interface Engine {acknowledge:(action:Record<string,unknown>)=>Promise<void>;read:()=>Promise<AppData|null>;status:()=>Promise<OfflineStatus>;enqueue:(p:Record<string,unknown>)=>Promise<{id:string;queued:true}>;sync:()=>Promise<unknown>;reviseIssue:(amount:string,note:string)=>Promise<void>;discardIssue:()=>Promise<void>;clear:()=>Promise<void>;backup:()=>Promise<unknown>}
declare global {var JasimFlowOffline:{createEngine:()=>Engine;SYNC_TAG:string};}
let instance:Engine|undefined;
export const offlineEngine=()=>instance||(instance=globalThis.JasimFlowOffline.createEngine());
export async function scheduleSync(){if(typeof window==="undefined")return;void offlineEngine().sync().catch(()=>{});try{const registration=await navigator.serviceWorker?.getRegistration();const sync=(registration as ServiceWorkerRegistration&{sync?:{register:(tag:string)=>Promise<void>}})?.sync;await sync?.register("jasimflow-outbox");}catch{}}
export async function prepareOffline(onReady:(ready:boolean)=>void){if(!("serviceWorker" in navigator))return;const check=(registration:ServiceWorkerRegistration)=>{const worker=registration.active;if(!worker)return;const channel=new MessageChannel();const timer=setTimeout(()=>channel.port1.close(),5000);channel.port1.onmessage=e=>{clearTimeout(timer);onReady(e.data?.ready===true);channel.port1.close();};worker.postMessage({type:"JF_STATUS"},[channel.port2]);};let existing:ServiceWorkerRegistration|undefined;try{existing=await navigator.serviceWorker.getRegistration();if(existing)check(existing);const registration=await navigator.serviceWorker.register("/sw.js",{scope:"/",updateViaCache:"none"});check(registration);registration.addEventListener("updatefound",()=>{const worker=registration.installing;worker?.addEventListener("statechange",()=>{if(worker.state==="activated")check(registration);});});void registration.update().catch(()=>{});}catch{if(!existing?.active)onReady(false);}}
export async function rememberDevice(){try{await navigator.storage?.persist?.();}catch{}}
export async function logoutDevice(){await offlineEngine().clear();if("caches" in window)await Promise.all((await caches.keys()).filter(k=>k.startsWith("jasimflow-")).map(k=>caches.delete(k)));const registration=await navigator.serviceWorker?.getRegistration();await registration?.unregister();}
export async function downloadDeviceBackup(){const backup=await offlineEngine().backup(),url=URL.createObjectURL(new Blob([JSON.stringify(backup,null,2)],{type:"application/json"})),a=document.createElement("a");a.href=url;a.download="JasimFlow-device-backup.json";a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
